### PR TITLE
[SDK-Core] Call App Action Support Added/Fixed CallAppAction BatchCall

### LINKED ISSUE #973: [SDK-CORE BUG] - CallAppAction batchCall doesn't work
## Bug Description

SDK-Core `batchCall` does not properly handle a `CALL_APP_ACTION` Operation. The batchable operation succeeds when called directly on the Superfluid host contract and when used with the JS-SDK, so the issue appears to be specific to SDK-Core.

## Relevant Environment Information

  - Project Type: node
  - Package version: 0.4.4
  - TypeScript/Javascript: Typescript
  - Blockchain interfacing library: ethers js
  - Node version: v16.6.1
  - Framework: Hardhat

## Reproduce Steps

1. Initialize framework in any environment
2. Create ethers signer
3. Create Operation with operation type "CALL_APP_ACTION"
4. Exec in a batch call
5. Transaction fails

## Expected Behavior

"CALL_APP_ACTION" with a function whose only argument is `bytes memory ctx` and that returns `bytes memory newCtx` should, when called by the SDK-Core batch call should succeed.

## Actual Behavior

The call always reverts with "Call Utils: target reverted".

## Context

It appears this may be due to the fact that the function selector is removed when the operation type is not "SUPERFLUID_CALL_AGREEMENT". This may be fixable by not removing the function selector when the operation type is "CALL_APP_ACTION".

Source: https://github.com/superfluid-finance/protocol-monorepo/blob/763ca6966046ad0f959aab86d11c5b50c9e00e70/packages/sdk-core/src/BatchCall.ts#L103

### PR DESCRIPTION
**Pull request by 0xdavinchee**
* Call App Action Operation creator added in Host class
* Call App Action support in batchCall fixed
* SuperAppTester basic contract added for testing call app action
* Tests added for:
    * call app action executed from operation
    * call app action executed from batch call
* **[BREAKING]** `BatchCall.getCallAgreementFunctionArgs` deprecated and removed
* `BatchCall.getCallDataFunctionArgs` is replacing it
* CHANGELOG updated and formatting cleanup
* yarn.lock updated

### CODE REVIEW

File: packages/sdk-core/tasks/setupTestEnvironment.sh [hunk 1]
```diff
@@ -16,4 +16,6 @@ yarn deploy-contracts-local
 cd ../sdk-core
 yarn generate:graphql-types
 yarn generate:abi-files
-yarn generate:web3-types
\ No newline at end of file
+yarn generate:web3-types
+# compile contracts before starting tests to generate typechain folder
+npx hardhat compile
```
Comment (kasparkallas) [inline packages/sdk-core/tasks/setupTestEnvironment.sh:21]: Tests slower now?

File: packages/sdk-core/src/Host.ts [hunk 2]
```diff
@@ -40,4 +40,24 @@ export default class Host {
...
     };
+
+    /**
+     * Creates an Operation of the `callAppAction` function on the host contract.
+     * @param app the address of the Super App you are calling
+     * @param callData the encoded callData for the function
+     * @param overrides ethers overrides object for more control over the transaction sent.
+     * @returns {Operation} an `Operation` class
+     */
+    populateCallAppActionTxnAndReturnOperation = (
```
Comment (kasparkallas) [inline packages/sdk-core/src/Host.ts]: The function name is the whole implementation. That's a bit weird.

File: packages/sdk-core/.gitignore [hunk 3]
```diff
@@ -4,3 +4,5 @@ coverage
 /src/abi
 /src/typechain
 *.generated.ts
+/typechain-types
```
Comment (kasparkallas) [inline packages/sdk-core/.gitignore:7]: We were including these before?

File: packages/sdk-core/tasks/setupTestEnvironment.sh (hunk 1 above)
Comment (0xdavinchee) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: yup, it'll take extra time to compile the contract

File: packages/sdk-core/src/Host.ts (hunk 2 above)
Comment (0xdavinchee) [reply packages/sdk-core/src/Host.ts]: touché, will rename as: `callAppAction`

File: packages/sdk-core/tasks/setupTestEnvironment.sh (hunk 1 above)
Comment (kasparkallas) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: Approximately how much slower?

File: packages/sdk-core/.gitignore (hunk 3 above)
Comment (0xdavinchee) [reply packages/sdk-core/.gitignore:7]: no `typechain-types` is generated from the `.sol` file when you run `hardhat compile`, the other `/src/typechain` folder is generated from abi files which we pull from `ethereum-contracts` as part of the build process
`artifacts` are also generated from contract compilation

File: packages/sdk-core/tasks/setupTestEnvironment.sh (hunk 1 above)
Comment (hellwolf) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: 1 pre-throw routing of the disk

Comment (kasparkallas) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: ~20 seconds

**Review by kasparkallas — APPROVED** [review]

File: packages/sdk-core/tasks/setupTestEnvironment.sh (hunk 1 above)
Comment (hellwolf) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: @0xdavinchee need harder hat

Comment (0xdavinchee) [reply packages/sdk-core/tasks/setupTestEnvironment.sh:21]: we actually timed it, it takes an extra 5s the first time locally, probably ~20s in build and in subsequent local test runs, almost instant because it won't recompile
